### ISSUE TITLE
"IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by Akanksha2511** [betteridiot/bamnostic#32]
Hi, 

Thanks for developing this tool. Works very well on windows. 

I have an issue regarding the head() function. 

It gives me `"IndexError: tuple index out of range"`. I have attached the example bam file for your reference. 

Actually, I want to do subsampling on my bam file and for this, I need the reads to be randomly selected. As I am unable to get the reads using similar steps provided on your Github page as:
 ```
for i, read in enumerate(bam):
    if i >= 3:
        break
    print read
```

I get the same error of "IndexError: tuple index out of range".

Any help regarding this issue will be much appreciated.

Thanks,

[bam_file.zip](https://github.com/betteridiot/bamnostic/files/3280291/bam_file.zip)

**Comment by betteridiot** [comment]
It appears that your first read is malformed some how. Since this is the case, `head` wont work since it always goes back to the first read. This is the same reason you can't iterate through the file freely (because of the `IndexError` on the first read). This is happening because the first read is listed as having a 0 length sequence. If it has a 0 length sequence. I can look at a way to overcome this, but the point is that there shouldn't be a 0 length sequence in a bam file in the first place.

```python
>>> import bamnostic as bs

>>>with bs.AlignmentFile('0.0005.bam') as bam:
...     print(next(bam))
```
```pytb
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/root/miniconda3/envs/bamops/lib/python3.7/site-packages/bamnostic/bam.py", line 1041, in __next__
    read = bamnostic.AlignedSegment(self)
  File "/root/miniconda3/envs/bamops/lib/python3.7/site-packages/bamnostic/core.py", line 219, in __init__
    self._seq_builder()
  File "/root/miniconda3/envs/bamops/lib/python3.7/site-packages/bamnostic/core.py", line 326, in _seq_builder
    self._byte_seq = unpack('<{}B'.format((self.l_seq + 1) // 2), self._range_popper(1 * ((self.l_seq + 1) // 2)))
  File "/root/miniconda3/envs/bamops/lib/python3.7/site-packages/bamnostic/utils.py", line 387, in unpack
    return out[0]
IndexError: tuple index out of range
```

**However**, if it skip the first read, everything else works fine:

```python
>>> import bamnostic as bs

>>>with bs.AlignmentFile('0.0005.bam') as bam:
...     try:
...         skipped  = next(bam)
...     except IndexError:
...         pass
...     for i in range(3):
...         print(next(bam))
```
```pytb
db665bd5-e816-4a9d-85eb-7e82c2fe42de    0   ENSMUST00000082421.1        13   60   3S18M2I17M2I20M1D6M3D29M1D31M1D5M1D29M1I14M1I51M2D26M1D12M2I6M1D30M2D16M3I19M3D34M2I3M1D14M1D26M2D9M2I5M1I9M4D36M1I6M3I6M1D17M1D8M1I10M3D12M2I15M2I5M1D43M1I33M1I26M1I19M1D6M1D5M1I12M2I34M2D12M2D3M1D25M1I5M3D21M1D7M1I3M1D8M2D1M2D25M2I5M1D12M1I6M1I31M2D35M1I22M1I3M1I30M4D9M1D20M3D11M1D34M   *   0       0    ACGCGAAAAACTTACCCATTATTTTTAAAATTATTAACCACTCTCATTCATTGACCTACCTGCCCATCCATTTCATCATGATGAAACTTTGGGTCCCTCTAGGAGTTCGCCTAATAGTCCAAATCATTCAGGTTTTTCTTAGCCATACACTACTTACCAGATAACAATAACAGCCTTCTTCATCAGTAACACACATTTGTCGAGACGTAAATTACGGGTGACTAATCCGATATACACGCAAACGGAGCCTCAATATTTTTATTTGCTTATATTCCACATGTCGGACGAGGCTTATATTATGGATCATACATTTATAGAAACACGCCGAAACATTGGAGTACTTCTGTTCGCGGTCATAGCCTCAGCATTTATAGGCTACACGCCTTCCATGAGGACAATATCATTCTGAGGTGCCACAGTTAACAAACCTCCTCTATCTAGCCATCCCATTGGAACAACCCTAGTCGAATGAATCTGAGGGGGCTTTCTCAGAGGTAGACAAGCCACCTTGACCCGATCTTCGCTCTTCCACTTCATACCATTTATTATTTCGCGGCCCTAGCAATTTCGTTTCCTCCTCTTCCTCCACGAAACAGGATCAAACAACCCATCAGGAATTAAACTCAGATGCAGATAAAATTCCATTTCACCCCCTACTATACAATCAAAGATATCCTTAGGTATCCTAATCATATTTTAATTTCATATTCCGTAGTATTAACTTTTCCCCGGACATACTAGGAGACCCAGACAACTATACCAGCTAATACTAACTTCCCACCCCATATTAAACCCGAAATGATTCCTATTTGCATACGCCATTTACGCTCTAATCCCAATAATTAGGTGTCCTAGCCTTAATCTTATCTTTATCCAATTTTAGCCCTAAATACCTTTTCCTTCATACCTTCAAGCAACGAAGCCTAATTCCGCCCAATCACACAAATTTTGTACTGAATCCATAGTAGCCAACCTACTTATCTTAAACGCTGAATTGGGGGCCAACAAGTAGAACACCCATTATCATTGCCAACTAGCCTCCATCTCATTCTCAATCATTTAATTCTTATACCAATCTCAGGAATTATCGAAG#&#%+../'$$#(&5:<>:@CE;/3?=BBD@@:7@/)*33/%$253-)%'*8986<B=9@A;=787.;==)437;>AB48DC7=@@=10888;,60'1$,5762(96$.''7=4.:;>97::(/&&((32/1-'&%%'6BBI@=<2-/7+&&1$#$%*(>8)&''4:/4=3691#&%',-&,5<;::3102<<C9:;94644/?7)<*46*'021-3<2?:5===8:5@7,%'#'+2631-)+',&5?>1+78//;3&265799@87887$46%5#&.3;,-./()AGE=88885278779://-(.11124;8+97>2..$+#&));99?11@99F:;<;)3'>5.$.4&(6445,?>??9+1<7//.*,,.67&/#$*/1%*;8=A<<B359$)4.*)/55652>=29D@@:;=B<:75$#*>EG?:3-3'2796$&%((''09<=7->4>9><>=71%21;+)()(*6::;+1&#39:;A=49%)(-+2"%%239+1;=;?@5+&$275.99B80'(1,9//$,648.8?900)(*+++&,3-$'%&&&*'+',2'#&,-**.-/0<6:34/4466&(*'+$*$:;=@763&,.8244@?/115=3*'3+9=:(,;:86237<?A2:;5975::<=09>?564/%$&-400,,1A@=77<<:14772;>>@,6/4->>>>&3.8.%3.619,-2;99.*66762%'*(#%$'$#*1*"%...4,23$%8</58**)&$-55)(.54;?6,%*%$($(87<8@@>1-08+%%%(*,)%'0.,,0#**4349/-:301=>5.,'*%$.143,')%&&)/)&$%('4/3(.4')07664.-2$0%-86<4>/;=<;?=?>>909/9*'%#%1&,&(38;;<*7::8811&3)*?><?.B(55;>=0&;/;AAJ=;('+1@<9A;=8+-8..16=54845:0&;?A876)=9<6(;A@=8:3)05@;:92,+./5=,-5634'58:)'%&%':@?;4*,:?;19?B@<:93&81$302:2/+6.'%&'.-.=<8966=0$*///.'+,.&)&*++++++*(,,,,%'+---+66786'(/.:@-----+.=332   AS:S:758    NM:C:122    cm:C:112    de:f:0.07649999856948853        ms:S:758  nn:C:0  rl:C:0  s1:S:620    s2:S:273    tp:A:P  ts:A:+
51ba54e0-bac4-4006-8a2c-af48338ec0a3    0   ENSMUST00000082421.1        21   60   5S28M1D2M2D23M4D57M2D4M3D11M2I8M1D23M3D41M1D97M2D5M1D14M2D15M1I5M2I1M1D32M1D53M1I30M1D1M1D57M1I21M1D10M2D6M1D58M1D4M2I5M1D26M2I11M8I17M2D2M1D44M1D14M1I2M1I68M1D33M2D2M1D20M1I5M1I4M1I10M1D22M1I20M1D10M1D7M2I13M1I2M2I8M1D6M1D44M2D4M2D42M1I20M2S    *   0   0   CGAAAACACCCATTATTTAAAATTATTAACCACCACTTTGACCTACCTGCCCCATCCATACTTCATGATGAAACTTTGGGTCCCTTCTAGGAGTCTGCCTAATAGTCCAAATCATCAGGTTTCTTAGCCATTTACCATACCTTCAGATACAATAACAGCCTTTTCAGTAACACACATTTGTTGAGACGTAAATTACGGGTGACTATCCGATATATACACGCAAACGGAGCCTCAATATTCTTTATTTGCTTATTCCTTCATGTCGGACGAGGCTTATATTATGGATCATATACATTTATGGATCTGAATATTGGAGTACTTACTGTTCGCAGTCATTAGCCTTAAGCATTTATAGGCTACGTCCTTCCATGAGGACAATATCATTCTGAGGTGCCACAGTTATTACAAACCTCCTATCAGCCATCCCATCATATTGGAACAACCCTAGTCGAATGAATTTAGGGGCTTCTCAGTAGACAAAGCCACCTTGACCCGATTCTTCGCTTTCCACTTCATTTCTACCATTTATTATCGCGGCCCAGCAATCGTTTTTCCTTTCCTCCACGAAACAGGATCAAACAACCCAACAGGATTAAACTCAGATGCAGATAAAATCCATTTTTCACCCTACTATACAATCAAAGATATCCTCAAGGTATCCTAATCTTTTTTTCATATTCTTAATTCTCAACCTGGTATTATTCTTCCCAGACATATTAGGAGACCCAGACAACTCATCTTATCAAACCTCATCTAAACACCCCACCCCATATTAAACCCGAATGATATTTCCTATCTGCATACGCCATTCTACGCTCAATCCCAATAAACTAGGAGGTGTCCTAGCCTTAATCATTATCCTAATTTTAGCCCTAATTTCCTCTTCCTTTCATACCTCAAGCAACGAAGCCTAATATTCCATCCCAATCACACAAATTTTGACTGAATCCTGTAGCCAACACCTACTTATCTTCAACGCCTGAATTGGGGCCATCAGTAGAACACCCATTTATTATCATTGGCCAACTAGCCTCCATCATTTCTCAATCATCTTAATTCTTATACCAATTTCAGGAATTAACTGCAGACAAAATACTAAAATTGC   $)>@B943)'(%&9:>>B@BCC8+)12/,:<03('%)%5531;A,/@B<:BA;>:<@;-##)10..8-3;=?CC6$40??37:8&/03<H5;2@-6;5/<E+),9>9=1?>+***97;@9&;(1;<?65+4+,,+,)(#'.'##472*+211)&&&1552%&&+35<:,432-5;21,;;=;>A6>-:5;<<<=823?+5:6//0$,+33%&'+5()/484?=;25=?<D/32+9=-<>&034328A17@>:1@:B>59??B>6=7>60'A<:7BD63?BIOA:D>CA('76:74105*.@?*%130)+&)98;5/7?0*,*+A900-4-(21300<<?6:-//636BA=>>/063531<>C:6712-**;A;A<:8((82,+*;2D?;6>5::6@=<<B>5,269;9>65.**2>A=B57778477-$%$)&,>79<;;4&56'43?3/9993*/'%*./-.9:.%32(=7:<>;ACHIKB9,*+.+A>:;DF=796,675:24()5/%+>312,%.'%$-;:<5@42CA-6?@;6(*45=<?<.)*)*+%%%1,%)$)$%9:7/B=>H?AB;:/3784-,,<;)%(1>A;;;<>=8)<=<744),26666<?3.551-.$+$$44/)*+=@BC@<:0*(2924655*($",)9>000/-0///)'&)+-(&,68769135911'%%$*/794+4,%)9?15#+-7;A+:11&&'&))3;79@@<<=8?@3(1($#$)$(*#-20++-%$#$%'1,++'%671(&3122+(4@@AB?C><@@>>:+'(9:=:@=4$*7888=<988916+/513(527;)441887533(0,,)$760:.-379>>3:?:-1'&#(0&06/.+104/08++++++*##-12&.,3(3)3.752/0124923(11,?D@9;@<<9-/--/&%7;??=/$$=BBHB9?B586-*97B<;6(+.+9?84.')%0323:?BA+%%&$%(-'$*14@:;734C@<;=5>?<@:3>?B;<A@AECE>>@A../.@<;>D3-*51579>5=;.*(.''+68741553$%478<<47><;;76<;6$17-29%''''&&&,//2(%((((('''''&&$$/$   AS:S:795    NM:C:110  cm:C:150    de:f:0.07249999791383743    ms:S:795    nn:C:0  rl:C:0  s1:S:751  s2:S:350    tp:A:P  ts:A:+
e6711cf6-0a41-4cef-87e5-3e0ed2accae3    0   ENSMUST00000082421.1        334  60   12M2D62M1D8M1I60M1I6M1I11M1D6M2D30M1I4M2D7M2I1M1D17M1D18M4D2M2D3M2D15M1I1M1I12M1D21M1D13M1D25M3I15M1D1M2D29M2D9M1D1M1D45M1I28M1I4M1I24M1D6M1I20M3I24M1I5M1D36M1D11M2I3M2D6M1D33M1D12M1D52M1D3M3D26M1I20M    *   0   0   ACCTGAAACATTAGTACTTCTACTGTTCGCAGTCATAGCCACAGCATTTATAGGCCACGTCCTTCCATGAGGACAATATCATCTCTGAGGTGCCACAGTTATTACAAACCTCCTATCAGCCATCCCATATATTGGAACAACCCTTAGTCGAAATGAATTTGAGGGGCTTCAGTAGACAAAGCCACCTTGACCCGATTCTTTCGTTCCACTCATATCTTACCATTTATTATATAGCCCTAGCAATCGTTTCCTTTCCACGAAACAGGATACTAAACAACCCATCGGATTAAACTCAGATGCAGATAAATTCCATTTCACCCTCATTTACAATCAAAGATATCCAAGGAGGTATCCTAATCAACTTAATTCACATAACCCTAGTATTAACTTCCAGACATATGGAGACCCAGACAACTACATACCAGCTAATCCACTAAACACCCCACCCCCATATTAAACCCGAATGATATTTCCATATTCTGCATACGCCATTCTACGCTCAATCCCAATAAAACTAGGAGGTGTCCTAGCCTTCTTAATCTTATCTATCCTAATTTTCAGCCCAATACCTTTCCTTCATACCTCAAAGCAACGAAGCCTATATTCCGCCCATAATCACAAATTTGTACTGAATCCTAGTAGCCAACCTACTTATTTAACCTGAATTGGGGCCAACCAGTAGAACACCCATTTATTATCATTGGCCAACTAGCCTCCATTCATTCTCAATCATCTTAATTTTTATACCAAATCTCAGGAATTATCGAAG   ,278A>==C+*6)<CD<:.&203<8>5(00-<58'13)33187;9?999/.+-$)&,26.//.0;96672?C:9;1,',.-.#+$9.&342=9A49=C@8&+9FF=CB>478+3532564)()56:;1+.$0:05795@9'>;$73<-&,'&#,4=45/=0)5?:<9-*47>54;665.'-//$','/A==:=F<945:.7-2##*&')()(+'1$&*&+((-,=<?:;*#%&.+7*0594<>6-1,1)4;4&)*(.=8>43233;72('$*87279>>>=.(,.$35677600?@F9A621468=?;0;+++..&'97&(-..(&$-(-2+**=8<;=1*3,;98(:=8;7.58:6&-)%&/8:+13&#&&(4888366245-0;810/25641/)'&&.3?::8)3+3++)((&#'%%"&*+8CHEC::.=A@A;67/,:=,'39;8;90*;DC??+8;>G9@E>>49@3>-$$$&,'28=<7(@8?=8/6*CC:='7.'')68700.4<8867+-0)**/1),/47:80''',>AD>12AD<+;2<=888133*'#)8341*/-$,<C5=4>544<5()5//6=C<<9>91/)385+&,(0//02010-$-,,*+,,0002??@>C:>@</'%)383)1/7361;@<B7:8-&&-('43BEDC:/8=<.:/''1>@99D;=7?<AA5<,104<7-//3AB:@B;43<9C?922<8/.01('/9999687,&&76565'&24387552%/$#*&38*****%)8''4   AS:S:560    NM:C:75     cm:C:95   de:f:0.07090000063180923    ms:S:560    nn:C:0  rl:C:0  s1:S:515    s2:C:209  tp:A:P  ts:A:+
```

**Comment by betteridiot** [comment]
Looking at the [BAM format](https://samtools.github.io/hts-specs/SAMv1.pdf), turns out that if `l_seq` is 0, then it is an omitted sequence (represented as `*`). Trying to think of a workaround here. Give me some time.

**Comment by betteridiot** [comment]
Check out the new version on `pip` now (or 7eda0795f30974b80126056dfa4bebd3a791c17c) for this fix. I am running checks now. When/if they pass, I will post an updated release here and on `conda`

**Comment by Akanksha2511** [comment]
Thanks for your quick reply. I haven't tested the new version from pip. But just wanted to let you know that if I filter the bam file with "-q 1" i.e select all the reads with MAPQ value > 1, I no longer get the error.
